---
title: "Asciidoc1"
date: 2020-09-06T23:03:01-07:00
draft: false 
---

= Source highlight lines
:source-highlighter: rouge 
:rouge-style: base16.monokai
:icons: font
:fonts: icons
:icon-set: fas
:stem: latexmath
:toc: right

[NOTE]
====
There are things to note!
====

== mathjax

stem:[E = mc^2]

[stem]
++++
\begin{equation}
x^2 + y^2 = z^2
\label{eq:sample}
\end{equation}
++++

This is a reference to the equation above stem:[\eqref{eq:sample}].

== ditaa

[ditaa,diagram-ditaa,svg]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....


== plantuml

[plantuml, diagram-classes, svg]     
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

== syntax highlighting

[source,python]
----
def hello:
  print("hello")
----

```python
def hello:
  print("hello")  <1>
```

<1> A little callout

== a2s

[a2s]
....

 .-------------------------.
 |                         |
 | .---.-. .-----. .-----. |
 | | .-. | +-->  | |  <--+ |
 | | '-' | |  <--+ +-->  | |
 | '---'-' '-----' '-----' |
 |  ascii     2      svg   |
 |                         |
 '-------------------------'

https://github.com/asciitosvg

[1,0]: {"fill":"#88d","a2s:delref":1}
....

== vega

vega::data/treemap.json[alt="treemap for flare"]

== vegalite

[vegalite]
....
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/movies.json"},
  "mark": "circle",
  "encoding": {
    "x": {
      "bin": {"maxbins": 10},
      "field": "IMDB Rating"
    },
    "y": {
      "bin": {"maxbins": 10},
      "field": "Rotten Tomatoes Rating"
    },
    "size": {"aggregate": "count"}
  }
}
....

== mermaid

[mermaid,mermaid-graph,svg]
....
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
....

== bpmn

bpmn::data/diagram.bpmn[format=svg,target="diagram",alt="bpmn diagram",width=300,height=200]

== nomnoml

[nomnoml]
....
[Pirate|eyeCount: Int|raid();pillage()|
  [beard]--[parrot]
  [beard]-:>[foul mouth]
]

[<table>mischief | bawl | sing || yell | drink]

[<abstract>Marauder]<:--[Pirate]
[Pirate]- 0..7[mischief]
[jollyness]->[Pirate]
[jollyness]->[rum]
[jollyness]->[singing]
[Pirate]-> *[rum|tastiness: Int|swig()]
[Pirate]->[singing]
[singing]<->[rum]

[<start>st]->[<state>plunder]
[plunder]->[<choice>more loot]
[more loot]->[st]
[more loot] no ->[<end>e]

[<actor>Sailor] - [<usecase>shiver me;timbers]
....
